/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "octopus_crawler_constants.h"



const octopus_crawlerConstants g_octopus_crawler_constants;

octopus_crawlerConstants::octopus_crawlerConstants() {
}



