/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef octopus_crawler_CONSTANTS_H
#define octopus_crawler_CONSTANTS_H

#include "octopus_crawler_types.h"



class octopus_crawlerConstants {
 public:
  octopus_crawlerConstants();

};

extern const octopus_crawlerConstants g_octopus_crawler_constants;



#endif
